import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/AppComponents/Navbar";
import { CartProvider } from "@/store/CartProvider";

export const metadata: Metadata = {
  title: "BLACK WOLF",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
